### ISSUE TITLE
cannot import name 'MarginType' from 'gotenberg_client.options'

### ISSUE THREAD

**Issue by myhubacct** [stumpylog/gotenberg-client#27]
Hi,

I am using paperless-ngx together with gotenberg. As soon a I try to import an mail file (*.eml) I get the following error, which seems to be related to gotenberg

```
[2024-08-12 11:50:01,910] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: cannot import name 'MarginType' from 'gotenberg_client.options' (/usr/lib/python3.12/site-packages/gotenberg_client/options.py)

Traceback (most recent call last):

  File "/usr/share/paperless/src/documents/tasks.py", line 151, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/share/paperless/src/documents/consumer.py", line 560, in run

    document_parser: DocumentParser = parser_class(

                                      ^^^^^^^^^^^^^

  File "/usr/share/paperless/src/paperless_mail/signals.py", line 2, in get_parser

    from paperless_mail.parsers import MailDocumentParser

  File "/usr/share/paperless/src/paperless_mail/parsers.py", line 12, in <module>

    from gotenberg_client.options import MarginType

ImportError: cannot import name 'MarginType' from 'gotenberg_client.options' (/usr/lib/python3.12/site-packages/gotenberg_client/options.py)
```

I would appreciate any help on this.

Thanks in advance

**Comment by stumpylog** [comment]
`MarginType` is properly defined:  https://github.com/stumpylog/gotenberg-client/blob/3ee137c559beffb9239b9dbe28ca4c1b0ca4b872/src/gotenberg_client/options.py#L88


I would suggest ensuring you have properly updated dependencies.
